name: Build Docker Image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '13 4 * * *'

jobs:
  build:
    strategy:
      matrix:
        version: [8]
        os: [rockylinux, almalinux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-rpmbuild:${{ matrix.os }}-${{ matrix.version }} --build-arg FROM=${{ matrix.os }}
